name: safe_learn
description: "Super-App JOJ Afrique - Gamification, Culture, Missions"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation
  go_router: ^13.0.0
  
  # State management
  flutter_riverpod: ^2.5.0
  
  # UI / Fonts
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  confetti: ^0.7.0
  shimmer: ^3.0.0
  
  # Carte
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # Utils
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
