name: safe_learn
description: "Super-App JOJ Afrique - Gamification, Culture, Missions"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation
  go_router: ^13.0.0
  
  # State management
  flutter_riverpod: ^2.5.0
  
  # UI / Fonts
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  confetti: ^0.7.0
  shimmer: ^3.0.0
  
  # Carte
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # Utils
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lion_3d.png
    - assets/images/festival.png
    - assets/images/concertYoussou.png
    - assets/images/imagePost.png
    - assets/images/goreeHeader.png
    - assets/images/activiteNgor.png
    - assets/images/activiteGoree.png
    - assets/images/beachParty.png
    - assets/images/explore_hero.png
    - assets/images/logo.png
    - assets/images/auth_lion.png
    - assets/images/olivia_avatar.png
    - assets/images/login_background.png
    - assets/images/group5.png
    - assets/images/flag_left.png
    - assets/images/flag_right.png
    - assets/images/athlete1.png
    - assets/images/athlete2.png
    - assets/images/rectangle65.png
    - assets/images/Rectangle 51.png
    - assets/images/Rectangle 53.png
    - assets/images/Rectangle 55.png
    - assets/images/Rectangle 57.png
    - assets/images/ellipse5.png
    - assets/images/ellipse6.png
    - assets/images/ellipse7.png
    - assets/images/image8.png
